spring.datasource.url=jdbc:h2:mem:studentgig
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

server.port=${PORT:8080}

spring.jackson.serialization.write-dates-as-timestamps=false